server:
  port: 8888
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: sample-temporal
  # temporal specific configs
  temporal:
    namespace: default
    connection:
      target: 127.0.0.1:7233
    workersAutoDiscovery:
      packages: pl.mbaranowski._4_springboot